version: "3"
services:
  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./db/psgl:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
  financial_api:
    image: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USER : ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_DATABASE : ${DB_DATABASE}
      DB_HOST : postgres
      DB_PORT : 5432
    depends_on:
      postgres:
        condition: service_healthy

